# Generated by Django 4.0 on 2022-10-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='ho',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
