# Generated by Django 4.0 on 2022-10-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_khachhang_ho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='dia_chi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='dien_thoai',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='mat_khau',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='ten',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
